/*
 * genius.h
 *
 * Created: 30/08/2024 13:27:27
 *  Author: gabri
 */ 

#ifndef GENIUS_H_
#define GENIUS_H_

#define geniusMaxCounter 8

typedef enum{
	GENIUS_INVALID_COLOR = 0,
	GENIUS_AZUL,
	GENIUS_VERMELHO,
	GENIUS_VERDE,
	GENIUS_AMARELO,
	GENIUS_CYAN,
	GENIUS_PURPLE,
	GENIUS_PINK,
	GENIUS_WHITE,
	ALL_GENIUS_COLORS
}GENIUS_CORES;

typedef enum{
	GENIUS_INITIALIZE = 0,
	GENIUS_WAIT_STEP,
	GENIUS_SETUP_STEP,
	GENIUS_SHOW_COLOR_STEP,
	GENIUS_INPUT_SETUP_STEP,
	GENIUS_INPUT_STEP,
	GENIUS_EVALUATION_STEP,
	GENIUS_CONCLUSION_STEP,
	GENIUS_EXIT_STEP,
	GENIUS_TOTAL_STEPS
}GENIUS_STEP;

typedef enum{
	GENIUS_WAIT_INPUT = 0,
	GENIUS_TURN_NOT_ENDED,
	GENIUS_NEXT_TURN,
	GENIUS_USER_LOST,
	GENIUS_USER_WON,
	ALL_GENIUS_CONLCUSION
}GENIUS_CONCLUSION;

void geniusHandler(unsigned char hardModeFlag);
void geniusInitialize(void);

#endif